name: Close-pr-issue

on:
  push:
    branches:
     - master
     - main

jobs:
  close-pr-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: Karthik-Nayak98/Close-pr-issue@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
