name: Close-pr-issue
description: Close PR and issue after merging to main or master branch.
on:
  push:
    branches:
     - master
     - main

jobs:
  close-pr-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: Karthik-Nayak98/Close-pr-issue@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
