name: Close-pr-issue

on:
  pull_request:
    types: [closed]

jobs:
  close-pr-issue:
    runs-on: ubuntu-latest
    steps:
    - uses: Karthik-Nayak98/Close-pr-issue@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
